### ISSUE TITLE
Code blocks don't work

### ISSUE THREAD

**Issue by jqln-0** [thefryscorer/hackdown#1]
See your screenshot on the front page:

![Image](http://i.imgur.com/sggcz4x.png)

Instead of putting the "go get..." instructions in a little code block, it displays the literal '>' and dumps the text in on the previous line.

**Comment by thefryscorer** [comment]
Blackfriday's markdown parser seems to be quite different from Github's or others I have used. For example:

```
This won't work.
> Quote Text
```

```
This will work.

> Quote text
```
